### PR TITLE
fix: change password

### LINKED ISSUE #266: (#157 #158) Add Change Password
Add Change Password to Mobile and Web

### PR DESCRIPTION
**Pull request by LazarVilotic**
-added change password buttons and forms to mobile and web
closes #266

### CODE REVIEW

File: server/vroom/src/main/java/org/example/vroom/controllers/UserProfileController.java [hunk 1]
```diff
@@ -47,4 +48,18 @@ public ResponseEntity<RegisteredUserDTO> updateMyProfile(
                 )
         );
     }
+
+    @PutMapping("/change-password")
+    public ResponseEntity<String> changePassword(
+            @AuthenticationPrincipal UserDetails userDetails,
+            @RequestBody ChangePasswordRequestDTO dto
+    ) {
+        registeredUserService.changePassword(
```
Comment (isidorakorda) [inline server/vroom/src/main/java/org/example/vroom/controllers/UserProfileController.java]: missing try catch block
